### ISSUE TITLE
Troubleshooting Resistors/LED Brightness

### ISSUE THREAD

**Issue by sdaless** [andydoro/IMA767_MEDP349_Fall2018#4]
When I was building the circuitry for the most recent homework, I initially had issues with one of the LEDs.  With the original setup I had, the light from one specific LED was so dim, I didn't notice it was blinking (and proceeded to troubleshoot my code, circuits, everything but the LED... lol).  

What fixed the issue was swapping out the original resistor with a weaker one.  Can anyone explain why this worked?  I notice that if I plug in multiple LED lights to a breadboard, they can affect each other's voltage, but I thought our breadboards were arranged in a way that made them function like parallel circuits?

**Comment by andydoro** [comment]
> (and proceeded to troubleshoot my code, circuits, everything but the LED... lol).

Troubleshooting / debugging is an important skill you'll need to develop to do physical computing, computer programming, etc. With physical computing it's 5X as difficult because you might have a hardware problem, a software problem, or both! Here's a handy video series: https://vimeo.com/channels/debugging

> What fixed the issue was swapping out the original resistor with a weaker one. Can anyone explain why this worked?

Ohm's law. V = I x R. Lower resistance will allow more current resulting in a brighter light from the LED. You can see this if you control the resistance to the LED using a potentiometer. 

Different colored LEDs actually have different voltage characteristics... red LEDs usually only want 2V while green or blue want around 3V. You can check their datasheets if you want to do the calculation. Then use Ohm's law or an LED calculator to figure out which resistor value you need: http://www.ohmslawcalculator.com/led-resistor-calculator

> I notice that if I plug in multiple LED lights to a breadboard, they can affect each other's voltage, but I thought our breadboards were arranged in a way that made them function like parallel circuits?

Depends on how you construct your LED circuit. You can connect your LEDs in series or parallel.
